#!/bin/bash
tail -n +2 | cut -f1 | sort | uniq -c | sort -nr | head -11 | tr -s   | cut -d  -f3
103-the_biggest_fan script that parses web servers logs in TSV format as input and displays the 11 hosts or IP addresses which did the most requests.
